# Generated by Django 3.1 on 2020-08-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField()),
                ('content', models.CharField(max_length=280)),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
